groups:
  - name: my_alert_rules
    rules:
      - alert: Instance_down
        expr: up == 0
        for: 1m
        labels:
          serverity: critical
        annotations:
          summary: "Instance {{$labels.instance}} running job - {{$labels.job}} is down"
          description: "Instance {{$labels.instance}} running job - {{$labels.job}} is down for more than 1 minute"
