route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  # receiver: 'web.hook'
  receiver: 'email'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
  - name: 'email'
    email_configs:
    - to: 'to@gmail.com'
      from: 'from@gmail.com'
      smarthost: 'smtp.gmail.com:587'
      auth_username: 'from@gmail.com'
      auth_identity: 'from@gmail.com'
      auth_password: gmail-app-password
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']
