version: '3.0'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    container_name: grafana
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
  monitoringapp:
    container_name: monitoringapp
    build: 
      context: ../monitoringapp
      dockerfile: Dockerfile
    expose: 
      - 12345
    ports:
      - "12345:12345"
    networks:
      - monitoring
networks:
  monitoring:
